#Name of the Work Flow to be displayed
name: Build Web App

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
        name: Checkout Code
      #Adding Msbuild to our runner(Windows)
      - name: Setup VS2019
        uses: warrenbuckley/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      #Adding Nuget to restore our project in runner(Windows)
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      #Restoring packages for our package
      - name: Restore NuGet Packages
        run: nuget restore SampleDemoProject.sln
      #Re-Building the project for verification
      - name: Build
        run: msbuild SampleDemoProject.sln /p:Configuration=Release
      #Publishing to the folder
      - name: Publish to folder
        #run: msbuild SampleDemoProject.sln /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl="bin\app.publish\" /p:PackageAsSingleFile=false
        #run: msbuild SampleDemoProject.sln /p:configuration=Release;platform="any cpu";WebPublishMethod=Package;PackageFileName="\MyFolder\package.zip";DesktopBuildPackageLocation="\MyFolder\package.zip";PackageAsSingleFile=true;PackageLocation="\MyFolder\package.zip";DeployOnBuild=true;DeployTarget=Package
        #run: msbuild SampleDemoProject.sln /p:configuration=Release /p:WebPublishMethod=Package /p:PackageFileName="bin\app.publish\package.zip" /p:DesktopBuildPackageLocation="bin\app.publish\package.zip"/p:PackageAsSingleFile=true /p:PackageLocation="bin\app.publish\package.zip" /p:DeployOnBuild=true /p:DeployTarget=Package
        run: msbuild SampleDemoProject.sln /p:configuration=Release /p:WebPublishMethod=Package /p:PackageFileName="D:\a\SampleDemoProject\package.zip" /p:DesktopBuildPackageLocation="D:\a\SampleDemoProject\package.zip" /p:PackageAsSingleFile=true /p:PackageLocation="D:\a\SampleDemoProject\package.zip" /p:DeployOnBuild=true /p:DeployTarget=Package
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          #local: D:\a\SampleDemoProject\SampleDemoProject\SampleDemoProject\bin\app.publish\
          local: D:\a\SampleDemoProject\
          remote: D:\Hosting\SampleDemoProject\
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
      # - name: Send mail
      #   #if: always()
      #   uses: dawidd6/action-send-mail@v2
      #   with:
      #     # mail server settings
      #     server_address: smtp.gmail.com
      #     server_port: 587
      #     # user credentials
      #     username: ${{ secrets.MAIL_USERNAME }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     # email subject
      #     subject: Deployed to development server succesfully
      #     # email body as text
      #     body: Mail Body
      #     # comma-separated string, send email to
      #     to: manogekumar@promantus.com
      #     # from email name
      #     from: Manoge Kumar
      #     content_type: text/html
      #     # Optional converting Markdown to HTML (set content_type to text/html too):
      #     convert_markdown: true
      # - name: Adding Application to IIS
      #   run: New-WebApplication -Name testApp -Site 'Default Web Site' -PhysicalPath D:\Hosting\SampleDemoProject -ApplicationPool DefaultAppPool
